// ignore_for_file: equal_keys_in_map

import 'dart:ui';

import 'package:get/get.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageController extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //       Persion Translation -------------------------------------------------------------------------------------------------------------
        'fa': {
          // passwords
          "Saved Passwords": "گذرواژه‌های ذخیره‌شده",
          "There are no passwords saved.": "هیچ گذرواژه‌ای ذخیره نشده است.",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Unknown": "نامشخص",
          "No Title": "بدون عنوان",
          "No Content": "بدون محتوا",
          "No Password": "بدون گذرواژه",
          "Created on: ": "ایجاد شده در: ",
          "Confirm Deletion": "تأیید حذف",
          "Delete this password?": "آیا این گذرواژه را حذف کنید؟",
          "Yes": "بله",
          "No": "خیر",
          "Update Password": "بروز رسانی گذرواژه",
          "Title": "عنوان",
          "Content": "محتوا",
          "Password": "گذرواژه",
          "Password copied to clipboard!": "گذرواژه در کلیپ بورد کپی شد!",
          "Password is deleted": "گذرواژه حذف شد",
          "Update": "بروز رسانی",
          "Cancel": "انصراف", "savepassword": "ذخیره گذرواژه",
          "Title": "عنوان",
          "Password": "گذرواژه",
          "Contentisrequired": "محتوا الزامی است.",
          "Titleisrequired": "عنوان الزامی است.",
          "Importance Level": "سطح اهمیت",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Success": "موفقیت",
          "Error": "خطا",
          "This password already exists in Firestore.":
              "این گذرواژه قبلاً در Firestore موجود است.",
          "Password saved.": "گذرواژه ذخیره شد.",
          "Yes": "بله",
          "No": "خیر",
          "Cancel": "انصراف",
          "Created on:":"ایجاد شده در:",

          // Links
          "Links": "لینک‌ها",
          "thereisnolink": "هیچ لینکی وجود ندارد.",
          "Confirm Deletion": "تأیید حذف",
          "Delete this link?": "آیا می‌خواهید این لینک را حذف کنید؟",
          "Yes": "بله",
          "No": "خیر",
          "Link copied to clipboard!": "لینک در کلیپ بورد کپی شد!",
          "update": "بروزرسانی",
          "Content": "محتوا",
          "Title": "عنوان",
          "Description": "توضیحات",
          "cancel": "انصراف",
          "Added": "ایجاد شده",
          "savethelink": "ذخیره لینک",
          "Add New Link": "لینک جدید اضافه کنید",
          "URL *": "لینک *",
          "Title *": "عنوان *",
          "Description": "توضیحات",
          "Importance Level": "سطح اهمیت",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Cancel": "انصراف",
          "Save Link": "ذخیره لینک",
          "Invalid URL format": "فرمت لینک نامعتبر است",
          "Metadata fetched": "متادیتا دریافت شد",
          "Could not fetch metadata": "نمی‌توان متادیتا را دریافت کرد",
          "the lenght should be more than ten": "طول باید بیشتر از ده باشد.",
          // Khaterat
          "Show Memories": "نمایش خاطرات",
          "No memories found.": "هیچ خاطره‌ای پیدا نشد.",
          "Error": "خطا",
          "Delete Memory": "حذف خاطره",
          "Are you sure you want to delete this memory?":
              "آیا مطمئن هستید که می‌خواهید این خاطره را حذف کنید؟",
          "Yes": "بله",
          "No": "خیر",
          "Update Memory": "بروز رسانی خاطره",
          "Title": "عنوان",
          "Content": "محتوا",
          "Level": "سطح",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Success": "موفقیت",
          "Memory updated.": "خاطره بروز شد.",
          "Video Player": "پخش کننده ویدیو",
          "Play Video": "پخش ویدیو",
          "Open File": "باز کردن فایل",
          "savememories": "خاطرات ذخیره کنید",
          "Title": "عنوان",
          "Content": "محتوا",
          "Select Level": "سطح را انتخاب کنید",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Camera Video": "ویدیو دوربین",
          "Gallery Video": "ویدیو گالری",
          "Upload Text File": "بارگذاری فایل متنی",
          "save": "ذخیره",
          "Titleisrequired": "عنوان الزامی است.",
          "Contentisrequired": "محتوا الزامی است.",
          "Content too long (max 500)": "محتوا خیلی طولانی است (حداکثر 500)",
          // Photos
          "Photos": "عکس‌ها",
          "There is no photo": "هیچ عکسی وجود ندارد.",
          "Delete Photo": "حذف عکس",
          "Are you sure you want to delete this photo?":
              "آیا مطمئن هستید که می‌خواهید این عکس را حذف کنید؟",
          "Cancel": "انصراف",
          "Delete": "حذف",
          "Deleted": "حذف شد",
          "Photo removed.": "عکس حذف شد.",
          "Add New Image": "عکس جدید اضافه کنید",
          "Tap to add image": "برای اضافه کردن عکس ضربه بزنید",
          "Title": "عنوان",
          "Importance Level": "سطح اهمیت",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Save": "ذخیره",
          "Error": "خطا",
          "This photo already exists in Firestore.":
              "این عکس قبلاً در Firestore موجود است.",
          "Success": "موفقیت",
          "Photo saved.": "عکس ذخیره شد.",
          // Home Page
          "Home Page": "صفحه اصلی",
          "Link": "لینک",
          "Memory": "خاطره",
          "Photos": "عکس‌ها",
          "Password": "گذرواژه",
          "Recent Activity": "فعالیت‌های اخیر",
          "Finance": "مالی",
          "Settings": "تنظیمات",
          "Deleted": "حذف شد",
          "This photo already exists in Firestore.":
              "این عکس قبلاً در Firestore موجود است.",
          "Success": "موفقیت",
          "Photo saved.": "عکس ذخیره شد.",
          "Error": "خطا",
          "Tap to add image": "برای اضافه کردن عکس ضربه بزنید",
          "Title": "عنوان",
          "Importance Level": "سطح اهمیت",
          "High": "بالا",
          "Medium": "متوسط",
          "Low": "پایین",
          "Save": "ذخیره",
          // Drawer
          "settings": "تنظیمات",
          "About me": "درباره من",
          "share": "شریک ساختن",
          // Finance
          "Source": "منبع",
          "Amount": "مقدار",
          "Income": "درآمد",
          "Expense": "هزینه",
          "Add Transaction": "اضافه کردن تراکنش",
          "Total Income": "کل درآمد",
          "Total Expenses": "کل هزینه‌ها",
          "Balance": "توازن",
          "Update Transaction": "به روزرسانی تراکنش",
          "Source": "منبع",
          "Amount": "مقدار",
          "Update": "به روزرسانی",
          "Cancel": "انصراف",
          "Delete Transaction": "حذف تراکنش",
          "Are you sure you want to delete this transaction?":
              "آیا مطمئن هستید که می‌خواهید این تراکنش را حذف کنید؟",
          "Yes": "بله",
          "No": "خیر",
          "My Finance": "مالی من",
          "Overview": "بررسی اجمالی",
          "Income": "درآمد",
          "Expenses": "هزینه‌ها",
          "Delete Transaction": "حذف تراکنش",
          "Are you sure you want to delete this transaction?":
              "آیا مطمئن هستید که می‌خواهید این تراکنش را حذف کنید؟",
          "Yes": "بله",
          "No": "خیر",
          "Update Transaction": "به روزرسانی تراکنش",
          "Source": "منبع",
          "Amount": "مقدار",
          "Update": "به روزرسانی",
          "Cancel": "انصراف",
          "Add Transaction": "اضافه کردن تراکنش",
          "Date Range": "محدوده تاریخ",
          "No expenses recorded yet.": "هنوز هیچ هزینه‌ای ثبت نشده است.",
          "Update Expense": "به‌روزرسانی هزینه",
          "Source": "منبع",
          "Amount": "مقدار",
          "Update": "به‌روزرسانی",
          "Cancel": "انصراف",
          "Delete Transaction": "حذف تراکنش",
          "Are you sure you want to delete this transaction?":
              "آیا مطمئن هستید که می‌خواهید این تراکنش را حذف کنید؟",
          "Yes": "بله",
          "No": "خیر",
          "About the Developer": "درباره توسعه دهنده",
          "Parwiz Mirzai": "پرویز میرزایی",
          "Flutter Developer": "توسعه دهنده فلاتر",
          "About Me:": "درباره من:",
          "I am a passionate Flutter developer with experience in building beautiful and functional mobile applications. I enjoy creating user-friendly interfaces and implementing the latest technologies to enhance user experience.":
              "من یک توسعه دهنده متعهد فلاتر هستم که تجربه ساخت برنامه‌های موبایل زیبا و کاربردی را دارم. از ایجاد رابط‌های کاربری کاربر پسند و پیاده‌سازی آخرین فناوری‌ها برای بهبود تجربه کاربری لذت می‌برم.",
          "Contact Me:": "با من تماس بگیرید:",
          "Email: mirzai.edc@gmail.com": "ایمیل: mirzai.edc@gmail.com",
          "LinkedIn: https://af.linkedin.com/in/parwiz-mirzai-34526b337":
              "لینکدین: https://af.linkedin.com/in/parwiz-mirzai-34526b337",
          "GitHub: https://github.com/parwiz-mirzai":
              "گیت‌هاب: https://github.com/parwiz-mirzai",
          "Phone: 0796203265": "تلفن: 0796203265",
          "My App": "برنامه من",
          "getstarted": "شروع کنید",
          "next": "بعدی",
          "skip": "رد کردن",
          "Moving Your Loads": "انتقال بارهای شما",
          "This is a personal data Management application that uses to save all the personal data.":
              "این یک برنامه مدیریت داده‌های شخصی است که برای ذخیره‌سازی تمام داده‌های شخصی استفاده می‌شود.",
          "Saving the data in this application includes Photos, Memories, Passwords, Links, and the most important is the Finance":
              "ذخیره‌سازی داده‌ها در این برنامه شامل عکس‌ها، خاطرات، رمزها، لینک‌ها و مهم‌ترین آن مالی است.",
          "This application has a simple user interface and it is a user-friendly app":
              "این برنامه دارای یک رابط کاربری ساده است و یک برنامه کاربر پسند است.",
          "Login": "ورود",
          "Username": "نام کاربری",
          "Password": "گذرواژه",
          "Donothaveanaccount": "حساب ندارید؟",
          "Signup": "ثبت نام",
          "usernameorpasswordisincorrect": "نام کاربری یا گذرواژه اشتباه است",
          "RegisterNewAccount": "ثبت حساب جدید",
          "Reenterpassword": "گذرواژه را دوباره وارد کنید",
          "Alreadyhaveanaccount": "قبلاً حساب دارید؟",
          "useralreadyexistspleaseenternewuser":
              "کاربر قبلاً وجود دارد، لطفاً کاربر جدیدی وارد کنید",
          "Authentication": "احراز هویت",
          "authenticate to access your information":
              "برای دسترسی به اطلاعات خود احراز هویت کنید",
          // settings
          "settings_theme": "حالت تاریک",
          "settings_language": "تنظیمات",
          "english": "English",
          "persian": "فارسی",
          "pashto": "پښتو",
          "settings_auth_required": " برای باز کردن برنامه احراز هویت نیاز است",
          "settings_use_biometric": "استفاده از اثر انگشت (در صورت موجود)",
          "login_with_pattern": "ورود با الگـو",
          "login_with_fingerprint": "ورود با اثر انگشت",
          "apply": "اعمال",
          "please_select_auth": "لطفاً روش احراز هویت را انتخاب کنید!",
        },
        // English

        'en': {
          // passwords
          "Saved Passwords": "Saved Passwords",
          "There are no passwords saved.": "There are no passwords saved.",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Unknown": "Unknown",
          "No Title": "No Title",
          "No Content": "No Content",
          "No Password": "No Password",
          "Created on: ": "Created on: ",
          "Confirm Deletion": "Confirm Deletion",
          "Delete this password?": "Delete this password?",
          "Yes": "Yes",
          "No": "No",
          "Update Password": "Update Password",
          "Title": "Title",
          "Content": "Content",
          "Password": "Password",
          "Password copied to clipboard!": "Password copied to clipboard!",
          "Password is deleted": "Password is deleted",
          "Update": "Update",
          "Cancel": "Cancel",
          "savepassword": "Save Password",
          "Title": "Title",
          "Password": "Password",
          "Contentisrequired": "Content is required.",
          "Titleisrequired": "Title is required.",
          "Importance Level": "Importance Level",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Success": "Success",
          "Error": "Error",
          "This password already exists in Firestore.":
              "This password already exists in Firestore.",
          "Password saved.": "Password saved.",
          "Yes": "Yes",
          "No": "No",
          "Cancel": "Cancel",
          "Created on:":"Created on:",
          // Link
          "Links": "Links",
          "thereisnolink": "There are no links.",
          "Confirm Deletion": "Confirm Deletion",
          "Delete this link?": "Delete this link?",
          "Yes": "Yes",
          "No": "No",
          "Link copied to clipboard!": "Link copied to clipboard!",
          "update": "Update",
          "Content": "Content",
          "Title": "Title",
          "Description": "Description",
          "cancel": "Cancel",
          "Added": "Added",
          "savethelink": "Save the Link",
          "Add New Link": "Add New Link",
          "URL *": "URL *",
          "Title *": "Title *",
          "Description": "Description",
          "Importance Level": "Importance Level",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Cancel": "Cancel",
          "Save Link": "Save Link",
          "Invalid URL format": "Invalid URL format",
          "Metadata fetched": "Metadata fetched",
          "Could not fetch metadata": "Could not fetch metadata",
          "the lenght should be more than ten":
              "The length should be more than ten.",
          // Khaterat
          "Show Memories": "Show Memories",
          "No memories found.": "No memories found.",
          "Error": "Error",
          "Delete Memory": "Delete Memory",
          "Are you sure you want to delete this memory?":
              "Are you sure you want to delete this memory?",
          "Yes": "Yes",
          "No": "No",
          "Update Memory": "Update Memory",
          "Title": "Title",
          "Content": "Content",
          "Level": "Level",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Success": "Success",
          "Memory updated.": "Memory updated.",
          "Video Player": "Video Player",
          "Play Video": "Play Video",
          "Open File": "Open File",
          "savememories": "Save Memories",
          "Title": "Title",
          "Content": "Content",
          "Select Level": "Select Level",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Camera Video": "Camera Video",
          "Gallery Video": "Gallery Video",
          "Upload Text File": "Upload Text File",
          "save": "Save",
          "Titleisrequired": "Title is required.",
          "Contentisrequired": "Content is required.",
          "Content too long (max 500)": "Content too long (max 500)",
          // Photos
          "Photos": "Photos",
          "There is no photo": "There is no photo.",
          "Delete Photo": "Delete Photo",
          "Are you sure you want to delete this photo?":
              "Are you sure you want to delete this photo?",
          "Cancel": "Cancel",
          "Delete": "Delete",
          "Deleted": "Deleted",
          "Photo removed.": "Photo removed.",
          "Add New Image": "Add New Image",
          "Tap to add image": "Tap to add image",
          "Title": "Title",
          "Importance Level": "Importance Level",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Save": "Save",
          "Error": "Error",
          "This photo already exists in Firestore.":
              "This photo already exists in Firestore.",
          "Success": "Success",
          "Photo saved.": "Photo saved.",
          // Home Page
          "Home Page": "Home Page",
          "Link": "Link",
          "Memory": "Memory",
          "Photos": "Photos",
          "Password": "Password",
          "Recent Activity": "Recent Activity",
          "Finance": "Finance",
          "Settings": "Settings",
          "Deleted": "Deleted",
          "This photo already exists in Firestore.":
              "This photo already exists in Firestore.",
          "Success": "Success",
          "Photo saved.": "Photo saved.",
          "Error": "Error",
          "Tap to add image": "Tap to add image",
          "Title": "Title",
          "Importance Level": "Importance Level",
          "High": "High",
          "Medium": "Medium",
          "Low": "Low",
          "Save": "Save",
          // Drawer
          "settings": "Settings",
          "About me": "About Me",
          "share": "Share",
          // Finance
          "Source": "Source",
          "Amount": "Amount",
          "Income": "Income",
          "Expense": "Expense",
          "Add Transaction": "Add Transaction",
          "Total Income": "Total Income",
          "Total Expenses": "Total Expenses",
          "Balance": "Balance",
          "Update Transaction": "Update Transaction",
          "Source": "Source",
          "Amount": "Amount",
          "Update": "Update",
          "Cancel": "Cancel",
          "Delete Transaction": "Delete Transaction",
          "Are you sure you want to delete this transaction?":
              "Are you sure you want to delete this transaction?",
          "Yes": "Yes",
          "No": "No",

          "My Finance": "My Finance",
          "Overview": "Overview",
          "Income": "Income",
          "Expenses": "Expenses",
          "Delete Transaction": "Delete Transaction",
          "Are you sure you want to delete this transaction?":
              "Are you sure you want to delete this transaction?",
          "Yes": "Yes",
          "No": "No",
          "Update Transaction": "Update Transaction",
          "Source": "Source",
          "Amount": "Amount",
          "Update": "Update",
          "Cancel": "Cancel",
          "Add Transaction": "Add Transaction",
          "Date Range": "Date Range",
          "No expenses recorded yet.": "No expenses recorded yet.",
          "Update Expense": "Update Expense",
          "Source": "Source",
          "Amount": "Amount",
          "Update": "Update",
          "Cancel": "Cancel",
          "Delete Transaction": "Delete Transaction",
          "Are you sure you want to delete this transaction?":
              "Are you sure you want to delete this transaction?",
          "Yes": "Yes",
          "No": "No",
          // About me
          "About the Developer": "About the Developer",
          "Parwiz Mirzai": "Parwiz Mirzai",
          "Flutter Developer": "Flutter Developer",
          "About Me:": "About Me:",
          "I am a passionate Flutter developer with experience in building beautiful and functional mobile applications. I enjoy creating user-friendly interfaces and implementing the latest technologies to enhance user experience.":
              "I am a passionate Flutter developer with experience in building beautiful and functional mobile applications. I enjoy creating user-friendly interfaces and implementing the latest technologies to enhance user experience.",
          "Contact Me:": "Contact Me:",
          "Email: mirzai.edc@gmail.com": "Email: mirzai.edc@gmail.com",
          "LinkedIn: https://af.linkedin.com/in/parwiz-mirzai-34526b337":
              "LinkedIn: https://af.linkedin.com/in/parwiz-mirzai-34526b337",
          "GitHub: https://github.com/parwiz-mirzai":
              "GitHub: https://github.com/parwiz-mirzai",
          "Phone: 0796203265": "Phone: 0796203265",
          // Onbording
          "My App": "My App",
          "getstarted": "Get Started",
          "next": "Next",
          "skip": "Skip",
          "Moving Your Loads": "Moving Your Loads",
          "This is a personal data Management application that uses to save all the personal data.":
              "This is a personal data Management application that uses to save all the personal data.",
          "Saving the data in this application includes Photos, Memories, Passwords, Links, and the most important is the Finance":
              "Saving the data in this application includes Photos, Memories, Passwords, Links, and the most important is the Finance.",
          "This application has a simple user interface and it is a user-friendly app":
              "This application has a simple user interface and it is a user-friendly app.",
// Authentications
          "Login": "Login",
          "Username": "Username",
          "Password": "Password",
          "Donothaveanaccount": "Don't have an account?",
          "Signup": "Signup",
          "usernameorpasswordisincorrect": "Username or password is incorrect",
          "RegisterNewAccount": "Register New Account",
          "Reenterpassword": "Re-enter password",
          "Alreadyhaveanaccount": "Already have an account?",
          "useralreadyexistspleaseenternewuser":
              "User already exists, please enter a new user",
          "Authentication": "Authentication",
          "authenticate to access your information":
              "Authenticate to access your information",
          // settings
          "settings_theme": "Dark Mode",
          "settings_language": "ُsettings",
          "english": "English",
          "persian": "Farsi",
          "pashto": "Pashto",
          "settings_auth_required": "Require Authentication to Open App",
          "settings_use_biometric": "Use Fingerprint (if available)",
          "login_with_pattern": "Login with Pattern",
          "login_with_fingerprint": "Login with Fingerprint",
          "apply": "Apply",
          "please_select_auth": "Please select authentication method!",
        },

        // Pashto translations (ps)
        'ps': {
          // passwords
          "Saved Passwords": "زخیره شوي گذرواژه",
          "There are no passwords saved.": "هیڅ گذرواژه ذخیره نه ده.",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Unknown": "نامعلوم",
          "No Title": "هیڅ عنوان نشته",
          "No Content": "هیڅ محتوا نشته",
          "No Password": "هیڅ گذرواژه نشته",
          "Created on: ": "ایجاد شوی په: ",
          "Confirm Deletion": "حذف تایید کړئ",
          "Delete this password?": "ایا غواړئ دا گذرواژه حذف کړئ؟",
          "Yes": "هو",
          "No": "نه",
          "Update Password": "زخیره شوي گذرواژه تازه کړئ",
          "Title": "عنوان",
          "Content": "محتوا",
          "Password": "گذرواژه",
          "Password copied to clipboard!": "گذرواژه په کلیپ بورډ کې کاپي شوه!",
          "Password is deleted": "گذرواژه حذف شوه",
          "Update": "تازه کړئ",
          "Cancel": "انصراف",
          "savepassword": "زخیره شوي گذرواژه",
          "Title": "عنوان",
          "Password": "گذرواژه",
          "Contentisrequired": "محتوا اړینه ده.",
          "Titleisrequired": "عنوان اړینه ده.",
          "Importance Level": "د اهمیت کچه",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Success": "بریالی",
          "Error": "خطا",
          "This password already exists in Firestore.":
              "دا گذرواژه دمخه په Firestore کې موجوده ده.",
          "Password saved.": "گذرواژه ذخیره شوه.",
          "Yes": "هو",
          "No": "نه",
          "Cancel": "انصراف",
          "Created on:":"ایجاد سوی ده:",
          // Links
          "Links": "لینکونه",
          "thereisnolink": "هیڅ لینک نشته.",
          "Confirm Deletion": "د حذف تصدیق",
          "Delete this link?": "ایا غواړئ دا لینک حذف کړئ؟",
          "Yes": "هو",
          "No": "نه",
          "Link copied to clipboard!": "لینک په کلیپ بورډ کې کاپي شو!",
          "update": "تازه کړئ",
          "Content": "محتوا",
          "Title": "عنوان",
          "Description": "توضیحات",
          "cancel": "انصراف",
          "Added": "اضافه شوی",
          "savethelink": "لینک ذخیره کړئ",
          "Add New Link": "نو لینک اضافه کړئ",
          "URL *": "لینک *",
          "Title *": "عنوان *",
          "Description": "توضیحات",
          "Importance Level": "د اهمیت کچه",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Cancel": "انصراف",
          "Save Link": "لینک ذخیره کړئ",
          "Invalid URL format": "د لینک فارمیټ نامعتبر دی",
          "Metadata fetched": "متادیتا ترلاسه شوه",
          "Could not fetch metadata": "متادیتا ترلاسه نشوه",
          "the lenght should be more than ten": "طول باید له لس څخه زیات وي.",
          // Khaterat
          "Show Memories": "خاطرات وښایاست",
          "No memories found.": "هیڅ خاطره نه ده موندل شوې.",
          "Error": "خطا",
          "Delete Memory": "خاطره حذف کړئ",
          "Are you sure you want to delete this memory?":
              "آیا تاسو پدې خاطرې حذف کولو کې باوري یاست؟",
          "Yes": "هو",
          "No": "نه",
          "Update Memory": "خاطره تازه کړئ",
          "Title": "عنوان",
          "Content": "محتوا",
          "Level": "د سطحه",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Success": "بریالی",
          "Memory updated.": "خاطره تازه شوه.",
          "Video Player": "ویدیو پلیر",
          "Play Video": "ویدیو پخش کړئ",
          "Open File": "فایل پرانیزئ",
          "savememories": "خاطرات ذخیره کړئ",
          "Title": "عنوان",
          "Content": "محتوا",
          "Select Level": "سطح وټاکئ",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Camera Video": "د کمرې ویدیو",
          "Gallery Video": "د ګالري ویدیو",
          "Upload Text File": "متن فایل پورته کړئ",
          "save": "ذخیره",
          "Titleisrequired": "عنوان اړین دی.",
          "Contentisrequired": "محتوا اړینه ده.",
          "Content too long (max 500)": "محتوا ډیر اوږده ده (اعظمي 500)",
          // Photos
          "Photos": "عکسونه",
          "There is no photo": "هیڅ عکس نشته.",
          "Delete Photo": "عکس حذف کړئ",
          "Are you sure you want to delete this photo?":
              "ایا تاسو پدې عکس حذف کولو کې باوري یاست؟",
          "Cancel": "انصراف",
          "Delete": "حذف",
          "Deleted": "حذف شو",
          "Photo removed.": "عکس حذف شو.",
          "Add New Image": "نو عکس اضافه کړئ",
          "Tap to add image": "د عکس د اضافه کولو لپاره ټک وکړئ",
          "Title": "عنوان",
          "Importance Level": "د اهمیت کچه",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Save": "ذخیره",
          "Error": "خطا",
          "This photo already exists in Firestore.":
              "دا عکس دمخه په Firestore کې موجود دی.",
          "Success": "بریالی",
          "Photo saved.": "عکس ذخیره شو.",
          // Home page
          "Home Page": "کور پاڼه",
          "Link": "لینک",
          "Memory": "خاطره",
          "Photos": "عکسونه",
          "Password": "پټ نوم",
          "Recent Activity": "وروستي فعالیت",
          "Finance": "مالي",
          "Settings": "تنظیمات",
          "Deleted": "حذف شو",
          "This photo already exists in Firestore.":
              "دا عکس دمخه په Firestore کې موجود دی.",
          "Success": "بریالی",
          "Photo saved.": "عکس ذخیره شو.",
          "Error": "خطا",
          "Tap to add image": "د عکس د اضافه کولو لپاره ټک وکړئ",
          "Title": "عنوان",
          "Importance Level": "د اهمیت کچه",
          "High": "لوړ",
          "Medium": "متوسط",
          "Low": "ټیټ",
          "Save": "ذخیره",
          // drawer
          "settings": "تنظیمات",
          "About me": "زما په اړه",
          "share": "شریکول",
          // Finance
          "Source": "سرچینه",
          "Amount": "مقدار",
          "Income": "عایدات",
          "Expense": "خرڅ",
          "Add Transaction": "تراکنش اضافه کړئ",
          "Total Income": "ټول عایدات",
          "Total Expenses": "ټول خرڅونه",
          "Balance": "توازن",
          "Update Transaction": "تراکنش تازه کړئ",
          "Source": "سرچینه",
          "Amount": "مقدار",
          "Update": "تازه کړئ",
          "Cancel": "انصراف",
          "Delete Transaction": "تراکنش حذف کړئ",
          "Are you sure you want to delete this transaction?":
              "ایا تاسو باوري یاست چې غواړئ دا تراکنش حذف کړئ؟",
          "Yes": "هو",
          "No": "نه",
          "My Finance": "زما مالي",
          "Overview": "کتنه",
          "Income": "عایدات",
          "Expenses": "خرڅونه",
          "Delete Transaction": "تراکنش حذف کړئ",
          "Are you sure you want to delete this transaction?":
              "ایا تاسو باوري یاست چې غواړئ دا تراکنش حذف کړئ؟",
          "Yes": "هو",
          "No": "نه",
          "Update Transaction": "تراکنش تازه کړئ",
          "Source": "سرچینه",
          "Amount": "مقدار",
          "Update": "تازه کړئ",
          "Cancel": "انصراف",
          "Add Transaction": "تراکنش اضافه کړئ",
          "Date Range": "د نیټې لړۍ",
          "No expenses recorded yet.": "تر اوسه هیڅ خرڅ ثبت شوی نه دی.",
          "Update Expense": "خرڅ تازه کړئ",
          "Source": "سرچینه",
          "Amount": "مقدار",
          "Update": "تازه کړئ",
          "Cancel": "انصراف",
          "Delete Transaction": "تراکنش حذف کړئ",
          "Are you sure you want to delete this transaction?":
              "ایا تاسو باوري یاست چې غواړئ دا تراکنش حذف کړئ؟",
          "Yes": "هو",
          "No": "نه",

          "About the Developer": "د پراختیا کوونکي په اړه",
          "Parwiz Mirzai": "پرویز میرزایي",
          "Flutter Developer": "فلاتر پراختیا کوونکی",
          "About Me:": "زما په اړه:",
          "I am a passionate Flutter developer with experience in building beautiful and functional mobile applications. I enjoy creating user-friendly interfaces and implementing the latest technologies to enhance user experience.":
              "زه د فلاتر یو متعهد پراختیا کوونکی یم چې د ښکلو او فعال موبایل غوښتنلیکونو په جوړولو کې تجربه لرم. زه د کارونکي دوستانه انٹرفیسونو په رامنځته کولو او د وروستیو ټیکنالوژیو پلي کولو کې خوند اخلم.",
          "Contact Me:": "زما سره اړیکه:",
          "Email: mirzai.edc@gmail.com": "برېښنالیک: mirzai.edc@gmail.com",
          "LinkedIn: https://af.linkedin.com/in/parwiz-mirzai-34526b337":
              "LinkedIn: https://af.linkedin.com/in/parwiz-mirzai-34526b337",
          "GitHub: https://github.com/parwiz-mirzai":
              "GitHub: https://github.com/parwiz-mirzai",
          "Phone: 0796203265": "تلیفون: 0796203265",

          "My App": "زما غوښتنلیک",
          "getstarted": "پیل کړئ",
          "next": "راتلونکی",
          "skip": "پرېږدئ",
          "Moving Your Loads": "ستاسو بارونه لیږدول",
          "This is a personal data Management application that uses to save all the personal data.":
              "دا یوه شخصي معلوماتو مدیریت غوښتنلیک دی چې د ټولو شخصي معلوماتو د خوندي کولو لپاره کارول کیږي.",
          "Saving the data in this application includes Photos, Memories, Passwords, Links, and the most important is the Finance":
              "په دې غوښتنلیک کې د معلوماتو ذخیره کولو کې عکسونه، یادښتونه، رمزونه، لینکونه، او تر ټولو مهم مالي شامل دي.",
          "This application has a simple user interface and it is a user-friendly app":
              "دا غوښتنلیک یو ساده کارن انٹرفیس لري او دا یوه کارن دوستانه غوښتنلیک دی.",
// Authentications
          "Login": "ورود",
          "Username": "کارن نوم",
          "Password": "پاسورډ",
          "Donothaveanaccount": "حساب نلرئ؟",
          "Signup": "ثبت نام",
          "usernameorpasswordisincorrect": "کارن نوم یا پاسورډ ناسم دی",
          "RegisterNewAccount": "نوې حساب ثبت کړئ",
          "Reenterpassword": "پاسورډ بیا دننه کړئ",
          "Alreadyhaveanaccount": "لا دمخه حساب لرئ؟",
          "useralreadyexistspleaseenternewuser":
              "کارن لا دمخه شتون لري، مهرباني وکړئ نوې کارن داخل کړئ",
          "Authentication": "احراز هویت",
          "authenticate to access your information":
              "د خپلې معلوماتو د لاسرسي لپاره احراز هویت وکړئ",
          // settings
          "settings_theme": "تاریک حالت",
          "settings_language": "تنظیمات",
          "english": "English",
          "persian": "فارسی",
          "pashto": "پښتو",
          "settings_auth_required": "د اپلیکیشن د خلاصولو لپاره تصدیق ته ترجیح",
          "settings_use_biometric": "د ګوتې نښه (که شتون ولري) وکاروئ",
          "login_with_pattern": "په نمونه سره ننوزئ",
          "login_with_fingerprint": "په اثرګوتې سره ننوزئ",
          "apply": "پلي کول",
          "please_select_auth": "مهرباني وکړئ د تصدیق طریقه وټاکئ!",
        }
      };

   // Human‐readable label (optional)
  final currentLabel = 'English'.obs;
  // Locale code used by GetMaterialApp
  final currentCode = 'en'.obs;

  /// Change language by code: 'en', 'fa', 'ps'
  Future<void> changeLanguage(String code) async {
    Locale locale;
    switch (code) {
      case 'fa':
        locale = const Locale('fa');
        currentLabel.value = 'فارسی';
        break;
      case 'ps':
        locale = const Locale('ps');
        currentLabel.value = 'پشتو';
        break;
      case 'en':
      default:
        locale = const Locale('en');
        currentLabel.value = 'English';
    }
    currentCode.value = code;

    // Update GetX locale
    Get.updateLocale(locale);

    // Persist code
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', code);
  }
}
